[project]
name = "MicroTiClassifierGUI"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==2.2.5",
    "onnxruntime==1.21.1",
    "pillow==11.2.1",
    "pyside6==6.9.0",
]
